
name: Release to the Maven Central

on:
  release:
    types: 
      - created
    
jobs:
  build-compiler-repository:
    name: Built the package
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
        
    - name: Cache the local Maven repository for better execution time
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
                    ${{ runner.os }}-maven-
    - name: Build the package with Maven
      run: mvn clean install --file pom.xml

    - name: Release to the Maven Central
      uses: samuelmeuli/action-maven-publish@v1
      with:
        gpg_private_key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
        gpg_passphrase: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
        nexus_username: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
        nexus_password: ${{ secrets.MAVEN_CENTRAL_TOKEN }}
        maven_goals_phases: clean install deploy
        maven_args: --file pom.xml
